---
  - name: apt update
    apt:
      update_cache: yes
    tags: update
  
  - name: apt dist-upgrade
    apt:
      upgrade: dist
    tags: update
  
  - name: set ip
    shell: bbb-conf --setip {{ inventory_hostname }}
    tags: update

  - name: set secret
    shell: bbb-conf --setsecret {{ bbb_secret }}
    notify: restart bbb
    tags: set_secret

#  - name: register bbb
#    shell: /root/register-bbb.sh bbb.messenger.schule {{ scalelite_prefix }} {{ ssh_key }}
#    tags: set_secret, register_bbb

  - name: replace turn-stun-servers.xml
    copy:
      src: turn-stun-servers.xml
      dest: /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml
      owner: bigbluebutton
      group: bigbluebutton
      mode: '0644'
    notify: restart bbb
    tags: turn_server
  
  - import_tasks: bbb-exporter.yml
    tags: bbb-exporter

  - name: copy bigbluebutton.properties
    template:
      src: bigbluebutton.properties.j2
      dest: /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
    notify: restart bbb
    tags: bbb_configuration

  - name: copy apply-config.sh
    copy:
      src: apply-config.sh
      dest: /etc/bigbluebutton/bbb-conf/apply-config.sh
    notify: restart bbb
    tags: bbb_configuration
